AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway to Kinesis Data Stream to AWS Lambda

Resources:
  # Define an AWS Kinesis Data Stream
  APIGKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1
  
  # Define an AWS Lambda and attach it to the application consumer
  ApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Runtime: python3.8
      Handler: app.lambda_Handler
      Tracing: Active
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt APIGKinesisStream.Arn
            StartingPosition: LATEST
            BatchSize: 100
            
Outputs:
  # Kinesis Data Stream name for data producers to use
  KinesisStream:
    Description: Kinesis Data Stream name
    Value: !Ref APIGKinesisStream